### PR TITLE
Apply quotes to the service name

### LINKED ISSUE #21: check-windows-service.rb problem when spaces in the service name
Needs quotes around the config service name when service name has spaces. 

I fixed this problem by adding the following:

```
cmd= 'tasklist /svc|findstr /r /c:' + '"'+ config[:service] +'"'
#cmd= 'tasklist /svc|findstr /i ' + '"'+ config[:service] +'\"'
temp = system(cmd)
```

### PR DESCRIPTION
**Pull request by bodgit**
## Pull Request Checklist

This fixes #21 and also stops a space-separated service name from matching other services.

I have to include the following to keep my employers legal team happy:

> This contribution is provided 'as is' and without any warranty or guarantee of any kind, express or implied, including in relation to its quality, suitability for a particular purpose or non-infringement. To the extent permitted by law, in no event shall the creator of this contribution be liable for any claim, damage or other liability, whether arising in contract, tort or otherwise, arising out of or in connection with this contribution.

#### General

- [x] Update Changelog following the conventions laid out on [Our CHANGELOG Guidelines ](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by majormoses** [comment]
@bodgit this looks good, can you please provide a testing artifact as described here: https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md#7-testing-artifacts

**Comment by bodgit** [comment]
If only there were some existing tests to use for inspiration... :stuck_out_tongue_winking_eye:

**Comment by majormoses** [comment]
@bodgit especially for windows...for anything else I would have pointed you at https://github.com/sensu-plugins/sensu-plugins-dcos for inspiration as that is what we are slowly trending towards.

**Comment by bodgit** [comment]
I was going to ask if this could make it out as a release but it looks like you're already prepping 2.2.1.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-windows/versions/2.2.1

**Pull request merged**
