### PR TITLE
Windows WMI metrics accumulate network traffic data over interval rather...

### PR DESCRIPTION
**Pull request by cloakedcode**
... than returning 1sec value each poll.

Per request in the [sensu-community-plugins PR](https://github.com/sensu/sensu-community-plugins/pull/1071).

### CODE REVIEW

**Comment by mattyjones** [comment]
@cloakedcode 

Thanks!

Could you take a look at the Travis output.  It is probably something simple as Rubocop is far more strict here.

**Comment by cloakedcode** [comment]
@mattyjones The problem is there's no .travis.yml in this repo. I'd copy it from another sensu-plugins repo but they're all a little different, not sure which to pull. Do you have a preference?

**Comment by mattyjones** [comment]
@cloakedcode  :facepalm

**Comment by mattyjones** [comment]
@cloakedcode 

Could do a rebase when you get a moment, that should clear up the issues.

Thanks1

**Comment by cloakedcode** [comment]
Rebase complete. The travis output looks too brief? Is this expected output?

**Pull request merged**
