### PR TITLE
Fixes for issue #16 and French

### PR DESCRIPTION
**Pull request by bgaillard**
## Pull Request Checklist

**Is this in reference to an existing issue?**

Fixes for issue #16 and French.
- Fix issue #16 for check-windows-cpu-load.rb
- Fix issue #16 for check-windows-ram.rb
- Fix issue #16 for metrics-windows-cpu-load.rb
- Fix issue #16 for metrics-windows-ram-usage.rb
- Fix issue #16 for metrics-windows-uptime.rb
- Add a .project to open the project in Eclipse (**just to easier work with Eclipse, do not hesitate do delete it if its not ok for you**)
#### General
- [X] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/) **--> I did not updated it because simply don't know the release date**
- [X] Update README with any necessary configuration snippets **--> No update is necessary**
- [X] Binstubs are created if needed **--> don't know if its applicable in my case**
- [X] RuboCop passes
- [X] Existing tests pass 
#### Purpose

Make plugins compliants with Operating Systems configured in French. This also add a first sample to helper other users add supports for other locales (Spanish, Italian, etc.).

### CODE REVIEW

**Comment by bgaillard** [comment]
After reflexion I think my implementation is perhaps a little "brittle". 

Perhaps it would be better to add a `--os-language` parameter whiuch would access an ISO 639-1 code. 

For example.
```
check-windows-disk.rb -w 85 -c 95 --os-language FR
```

What do you think about that ?

**Comment by eheydrick** [comment]
I think passing in the language would work well. Or is there an environment variable or other command that could be used to determine the language setting?

**Comment by majormoses** [comment]
@bgaillard any plans to circle back to this?

**Comment by majormoses** [comment]
@eheydrick From what I googled (exists as far back as XP) and validated (at home on windows 10) we could get it from `systeminfo.exe` which returned something like this:
```
PS C:\Users\majormoses> systeminfo.exe | findstr "Locale"
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
```

It looks like there might also be some registry values we can pull from as well: http://windowsitpro.com/systems-management/where-registry-language-setting-each-user-stored which has 2 registry entries to check I guess

Honestly I have no idea how we should go about it, someone with more windows chops should probably comment here...

**Comment by eheydrick** [comment]
Interesting, that looks promising.

**Comment by majormoses** [comment]
Lets take this back into the issue to discuss this is too brittle imho.

**Pull request closed without merging**
